### ISSUE TITLE
UI improvements to Action page

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/swoptact#14]
* Remove map and address fields.
* Each Action is either a “terminal” Action or a “prep” Action. This will be expressed via a new field “prep/terminal.”  If prep, then we will show another field that links to the terminal Action.  They will have several planning/prep meetings before any action. The prep meetings would have the action Action as their terminal Action.  Most Actions, then, will be of the "prep" variety, and will link to a terminal Action (e.g. "Rally with the Governor" or similar).
* Add "tags" to each Action.  This system would be for admins, who will control tag namespace and use them for reporting (possible tags: “housing,” “TTM”).  The number of tags is unlimited.  New tags are defined by users.
* Add 200-char "Action Description" field (reads something like: “education, parent mentors, pre-vacation meeting”).  This will later be used by admins to assign tags.  It is fine if this is left empty.
* On a cosmetic level, the Action page should show name, description, and tags horizontally across the top.
* From the Action page, users should still be able to add a Participant to the Action (regardless of spreadsheet handling page, #13), but via a simple dropdown, not the current horizontal filter setup.  Users found the filter confusing/distracting.
* Rename “site” to “location”

**Comment by cecilia-donnelly** [comment]
Tags moved to issue #27.  Still need to make the cosmetic changes mentioned above and add a terminal event link.

**Comment by cwebber** [comment]
@cecilia-donnelly asked me to look into why the inline representation of the many-to-many display of "participants" wasn't showing up as anything other than a dropdown.  Django's docs [appear to give the answer for this](https://docs.djangoproject.com/en/1.7/ref/contrib/admin/#working-with-many-to-many-models) but in reality it seems that Cecilia has correctly executed the advice from this and given [other conversations on the internet](http://stackoverflow.com/questions/10904848/adding-inline-many-to-many-objects-in-django-admin), very confusingly seeing the many to many dropdown is "expected"??? Which doesn't seem right.

Suggestions on that thread are that we subclass the form and modify the [.form attribute](https://docs.djangoproject.com/en/1.7/ref/contrib/admin/#django.contrib.admin.ModelAdmin.form) in order to get the behavior we want.  Which, okay, though that seems like a surprising amount of work for something that seemed implied like it would work having followed the docs' instructions for many2many fields.

**Comment by cecilia-donnelly** [comment]
^ see issue #13 for the comment above.

**Comment by cecilia-donnelly** [comment]
- only show "terminal event" if "is prep" is checked
- rename is_prep to "This meeting is part of a major action:" and then terminal event to "Major action:"
- Make time optional and display as hourly dropdown and am/pm dropdown.  Remove "now" and "today" options.

**Comment by cecilia-donnelly** [comment]
Remaining:
* [ ] Make "major action" show up on same line as is_prep checkbox, and show/hide depending on value of is_checked
* [ ] return time to page as described above

**Comment by cecilia-donnelly** [comment]
See #97 and #28.  The simple UI changes are done, so I'm closing this issue.
