### ISSUE TITLE
Sign-in sheet: "New" remains post autocompletion, until tab away

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/swoptact#147]
"New" should disappear after we choose an institution from the autocompletion dropdown, but currently it stays if we arrow down in the list until we tab away.  It disappears correctly if a user types out the whole institution name, but obviously that isn't the expected workflow.

**Comment by cwebber** [comment]
We can probably do this, though there's a reason the functionality is as it currently is: the option isn't actually "selected" yet on going through the list.  Tabbing away completes selection, as does clicking.  Hitting escape will "cancel" and the value goes back to its original state.

I'm trying to look into this now but it does mean getting the value from not-the-input-itself I think, since the value hasn't actually changed I think?

**Comment by cwebber** [comment]
Hm, I may be wrong.  The event may not be being triggered.  I'm looking further, but my initial assumption that I could simply bind my existing function to the "focus" or "close" events doesn't seem to be working

**Comment by cwebber** [comment]
I got things to the point where I could trigger the event, but something is wrong... there is some kind of race condition and it only works some of the time for selecting the other UI elements this way. :\

**Comment by cwebber** [comment]
Okay, @cecilia-donnelly pointed out what should have been the obvious :)  There's no need to do an ajax request when something is selected from the dropdown... if it's on the dropdown, it's not [NEW]!

With that insight, I managed to round this off and close this issue out!
