### ISSUE TITLE
Advanced Search

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/swoptact#185]
User stories brought over from #24:

Sandra is an organizer at SWOP who has a general understanding of the different campaigns (sets of actions) that SWOP is working on. She needs information about specific people that she is meeting with, and meta information about participation across actions and sets of actions. For all of these searches, the time period may be specified or unspecified. It might be a grant period or the past year, or any pair of dates.

- Sandra needs to find Theodore Rose's phone number, so she searches for him and looks at his record.
- Sandra wants to see a list and count of people who have been involved in the set of actions planned by a given organizer within a period of time.
- Sandra wants to see a list and count of the people who attended a given action.
-  Sandra needs to find a list and count of people who attended actions leading up to a given "major action" within a period of time.
-  Sandra wants a list of the institutions whose members attended a given action.
-  Sandra wants a list of the institutions whose members attended actions leading up to a given "major action" within a period of time.

Allie is an admin at SWOP who needs meta information about participation in actions and sets of actions across SWOP in order to report to funders. She needs everything that Sandra needs, as well as:

-  Allie needs a list and count of the people who attended actions with a given tag within a period of time.
-  Allie needs a list and count of the institutions whose members attended actions with a given tag.

**Comment by cecilia-donnelly** [comment]
@xray7224, thanks so much for your work on this!  We're quite a bit of the way there.

Questions (and comments) about functionality:

- We need to add date ranges for all searches.
- When we search for participants by institution, can the results be just a list of participants, *not* grouped by action?  Currently we get a list of actions without participants, if an institution without participants is chosen.
- I'm not sure how the institution search works.  When I search on a tag that only one of the institutions has, I still get all of them.  Similarly, when I put in an action that has many attendees, some of whom are linked to institutions, I still get a list of all institutions, with "No search results found" following each one.
- Implementation detail question: do we assume events are major actions unless they have a major action specified, or only if they've been added to some other action as a major action? (I think the second is preferable, since there might be some meetings that aren't prep for anything in particular but also shouldn't be called major).
- I couldn't get any results when searching for participant by both action and institution.  I would assume that this would find people who had both attended the action and were linked to the institution.  Is that right?
- Can we get counts of participants and prep actions when searching on a major action?  Something like:
```
Number of total participants: 
Number of prep actions:
```

Some UI suggestions follow here.  I'm very open to other ideas from everyone.

- Generally, the UI may need to change based on what is chosen from the dropdown.  For example, the action search needs an organizer field so users can search by the participant who organized an action.  Similarly, I don't think we need the exclude checkboxes for actions when we're searching for participants and institutions.
- I'm not sure what a user is supposed to put in the "participant" input box.  The actions, institutions, and tags all make sense, but I can't think of a time when I'd want to enter a participant.  What do you think?  Or can we remove this?
- I _love_ that searching by major action returns all the prep actions, too!  I think we can make it more clear that that's happening by separating the results into "prep actions" and "major action."

@xray7224, this looks great!  I think @nttaylor and I can probably tackle some of the UI changes, and probably some of the functionality if that would be helpful.  Despite this long comment, I think we're getting close with this -- thank you!

**Comment by xray7224** [comment]
I have fixed a lot of the issues that you brought up in https://github.com/OpenTechStrategies/swoptact/commit/025d50f791831dcdc8d47df7d4e3ff49db1246bb. Going through them:

- Date ranges added
- Participant searching, when you select participant it only shows participants
- The tags only worked against events, I have added it so it works with Events and Institution, the new fields should make that obvious.
- I assume major events are major events when is_prep is set to False, I don't pay any attention to if they have a major event or not when deciding if they're major or minor.
- I've tested searching for events and institutions works fine, let me know if you still experience this maybe attaching the data used and the query.
- We can get a count of events and minor events and such, I've not added this as of yet, it wouldn't be as easy as you might imagine but I can see what we can do if it's desirable.


- It's what i did initially, I think I could go back and pull the JS out though I suspect you don't need this because even when searching for participants or institutions you might still want to specify the event organizer e.g. you are searching for participants but you want to search for participants that participated in a major event with a specific organizer. You would select Participants in the drop down box and you would enter the event organizer and it would find the events and the display the participants who participated in it.

- The participant box could be used for several things, maybe you want to easily see the events that a participant participated in, in this case you would enter the participant and choose from the autocomplete and then select "Actions" from the drop down. You could also want to do a search on a partial name for example to find all the participants who's name contains "Harry" or some such.

- Separating major and minor events in the results page is doable. I haven't done it yet but, not sure how best to do it in the current code.

**Comment by cecilia-donnelly** [comment]
@xray7224 thanks for the detailed responses!  More from me:

> - Date ranges added

- Thanks!  I should have made this clear, but I think we can skip the time fields (I can make this change).

> - Participant searching, when you select participant it only shows participants

- Perfect, thank you

> - The tags only worked against events, I have added it so it works with Events and Institution, the new fields should make that obvious.

- Yes, they do make it obvious.  Should we only show the "Institution tags" input when users are searching on Institution and the same for Actions?  

> - I assume major events are major events when is_prep is set to False, I don't pay any attention to if they have a major event or not when deciding if they're major or minor.

- Thanks.  That makes total sense.

> - I've tested searching for events and institutions works fine, let me know if you still experience this maybe attaching the data used and the query.

-  Will do if I continue to run into it!

> - We can get a count of events and minor events and such, I've not added this as of yet, it wouldn't be as easy as you might imagine but I can see what we can do if it's desirable.

- If adding counts isn't easy (I'm curious about why that is and look forward to learning more) then we don't need to do it right away.

> - It's what i did initially, I think I could go back and pull the JS out though I suspect you don't need this because even when searching for participants or institutions you might still want to specify the event organizer e.g. you are searching for participants but you want to search for participants that participated in a major event with a specific organizer. You would select Participants in the drop down box and you would enter the event organizer and it would find the events and the display the participants who participated in it.

- Your explanation of keeping the participant field so that users can search by organizer makes perfect sense, but right now when we add a participant as an organizer, that person is _not_ automatically added as an attendee.  So, maybe we need another issue to do that, but we should probably change the UI so that it's more obvious that it's searching for fellow attendees of actions with the person being used a filter...

> - The participant box could be used for several things, maybe you want to easily see the events that a participant participated in, in this case you would enter the participant and choose from the autocomplete and then select "Actions" from the drop down. You could also want to do a search on a partial name for example to find all the participants who's name contains "Harry" or some such.

- Okay, thanks!  That makes sense.  I'll have to enlist you for help when writing the docs for this section.

> - Separating major and minor events in the results page is doable. I haven't done it yet but, not sure how best to do it in the current code.

- If it's not too hard then I still think it would be useful.

A couple other ideas:

- Searching for participants with no fields filled in doesn't return all participants, which I would expect it to do.  What's going on there?
- For me, the calendar datepicker only shows up on the start date, not on the end date.  I'm looking into that!
- Do we need a "clear filters" button?  I think it would be nice, but could be persuaded to leave it for now.

**Comment by xray7224** [comment]
> Should we only show the "Institution tags" input when users are searching on Institution and the same for Actions? 

I don't think so, the selector on what you're searching for is purely to format the results and decide how they should be grouped, all the search fields do the exact same thing regardless of what is searched (or they should at least).

If you fill in any institution data  (either in the institution search box or the institution tags) then even if you're using searching for events or actions it will still filter on what you entered. This could be useful if for example someone was searching for Events that some institutions with a specific tag had contacts who attended.

> If adding counts isn't easy (I'm curious about why that is and look forward to learning more) then we don't need to do it right away.

I can try and add it tomorrow, it's complicated as we have so many different views and filters and having the text and the counts display might be complicated but i'll try and think of a good solution to get it to us to have counts for the results.

> Your explanation of keeping the participant field so that users can search by organizer makes perfect sense, but right now when we add a participant as an organizer, that person is _not_ automatically added as an attendee.  So, maybe we need another issue to do that, but we should probably change the UI so that it's more obvious that it's searching for fellow attendees of actions with the person being used a filter...

Sure, I'll make a label to make it clearer you're searching for attendees and an extra filter can be added for searching for organizers. Will do for tomorrow.

> Okay, thanks!  That makes sense.  I'll have to enlist you for help when writing the docs for this section.

Sure :) I suspect the docs will be quite complex, there are a lot of filters.

> If it's not too hard then I still think it would be useful. (regarding major and minor separation on results page)

Sure, I can try and do this also, the reason it's a little more difficult than normal is currently there is just one set of code for handling the results for everything you select and because of that the major and minor things are mixed. To do this I'll have to put them in the context separately and try and get code which either does a different thing if I'm displaying events to handle this or to make some generic system, not sure which is best yet.

> A couple other ideas:
>
> - Searching for participants with no fields filled in doesn't return all participants, which I would expect it to do.  What's going on there?

Mmm yeah, don't know of a good way to solve this. I actually start most of the filters based off `Event.objects.all()` and go on from there building up the results and doing more filtering... The issue is fitting the participants in who aren't in an Event as they're not in my base query. I'll try and figure something out, it's not immediately obvious what that should be though. I welcome suggestions.

> - Do we need a "clear filters" button?  I think it would be nice, but could be persuaded to leave it 
for now.
Probably :) Should be trivial to add.

**Comment by cecilia-donnelly** [comment]
The major remaining piece of this is to be able to search for "participants" and have all participants returned, not just those that have attended an event.  One subset of this is to find all the participants associated with a particular institution.  I didn't include this as a user story, but a user has asked for it (in "SWOP Observations 20150921," for reference).

Sorry I didn't think of that one originally!  What do you think, @xray7224?  Currently, if I search for "Participants" and only fill in the Institution, no results are returned.

**Comment by cecilia-donnelly** [comment]
I haven't had any luck using the advanced search with institutions this go-around.  Examples:

Search for "Institutions" with organized by: Eustace Solares and all other fields empty returns no results.  I had set Eustace Solares as the organizer of the "Board Meeting" action.

Search for "Institutions" with Institution Tags: ttm and all other fields empty returns no results (it should return at least "Test Institution").

**Comment by cecilia-donnelly** [comment]
Merged and deployed on 2015-10-05.
