### ISSUE TITLE
Saving participant with invalid phone number crashes app

### ISSUE THREAD

**Issue by nttaylor** [OpenTechStrategies/swoptact#211]
When adding or editing a new participant, an invalid phone number causes an error when "save changes" or "done" is clicked (see screenshots below). This does not occur with a valid phone number or no phone number.
![screenshot_crop](https://cloud.githubusercontent.com/assets/12848962/10083692/37b51922-62c5-11e5-92e4-8359c1c92dc7.png)

![screenshot_error_crop](https://cloud.githubusercontent.com/assets/12848962/10083699/3e2d51d4-62c5-11e5-8656-245d55586712.png)

**Comment by cwebber** [comment]
@nttaylor Your analysis on IRC that this was probably related to #78 was spot-on.  The widget I put together was designed to show the appropriate representation for an integer based foreign key, but in the case of a form error, the form hadn't been "converted" to an integer yet, because it wasn't yet saved as a foreign key.  As such, any form that needed to come back with user corrections still had the text in the widget, but looking up text as a foreign key doesn't make sense, especially since it was looking up a reference that might not even exist yet.  Fixed!

**Comment by cecilia-donnelly** [comment]
See 3584ea0

**Comment by cwebber** [comment]
Guess I forgot that # symbol!
