### ISSUE TITLE
Rename "Save" to "Done" everywhere

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/swoptact#37]
Also, where we show the "Archive" and "Done" buttons, include the model name.  (e.g. Archive Action)

**Comment by cecilia-donnelly** [comment]
On the sign-in sheet, move the "Done" button up to the same row as the "Add New" button.

**Comment by cwebber** [comment]
Doing this via templates is going to make it so that this application is much, much harder to keep upgraded in the future, because we'll override many Django core templates just to change a word.  Then when Django updates those changes, our tweaked templates won't inherit them.

Maybe we can do this via Javascript instead.  That will have the awkward aspect that "Save" will suddenly switch to Done after the page loads, but I think it'll be easier to maintain in the long run.

**Comment by cwebber** [comment]
Done.  And, oh right!  I used jQuery's [.ready()](http://api.jquery.com/ready/) so there's no "after page loads" malarky.
