### ISSUE TITLE
Reformat phone number fields

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/swoptact#5]
The phone number field currently only takes phone numbers in an international format: a plus sign and 10 digits following.  Users will expect it to take phone numbers of the form (###) ###-#### and/or ###-###-####.  

Similarly, the date field should offer a pop-out calendar and/or guidance about format.

The time field should take something like "7pm" instead of forcing users to enter military time.

All fields except first and last name should be optional.

**Comment by xray7224** [comment]
We should fix it so that it accepts local format in addition to international format. If we are to accept numbers like that we need to be very careful that they're not stored in the database with this formatting and we remove it prior to storage and if we want to display it again when the user see's it that we re-add it on display.

The hyphens and parentheses are just formatting and they are not part of the number itself. I wonder if we can tie this in with django's l10n as it's specific to US.
