### ISSUE TITLE
Sign-in sheet: correct phone number format 

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/swoptact#51]
Phone numbers should appear in US format, not in international format.

**Comment by cwebber** [comment]
It looks like phonenumber_field only supports international formatted phone numbers so we will have to roll this ourselves.

**Comment by cwebber** [comment]
Alternate option is we can modify the field representation to append the +1 automatically, which might be a reasonable route

**Comment by cwebber** [comment]
AFAICT since this involves removing the current implementation we're using for this field, and that may have migration complications as well as writing an entirely new field, this is not easy, so I removed that label.

**Comment by cwebber** [comment]
Another option might be to subclass the phone type and add a from_national method.  This might be the nicest approach, and doesn't require any migration complications for certain.

**Comment by cwebber** [comment]
So it turns out that this *was* easier than I expected.  I didn't realize that this had been done before and that you could provide a national number format and it worked fine.  I *thought* I had tested with that form earlier, but evidently not.

Anyway, fixed!  Thanks to @xray7224 for helping direct me on how to resolve this.
