### ISSUE TITLE
Move done button to nearer the fields it affects

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/swoptact#70]
The done button sometimes is too far right.  (Perhaps this can be solved like #37?).

**Comment by cwebber** [comment]
Which "Done" button, the one on the lower right I assume, not the one on the ajax form? (The ajax form, I'm not sure how it could be moved any further left since it's flushed left in the column, but the other one could be moved)

Where would you want this moved?  Just padded a bit from the side?  If it's the one on the lower right this could be easy to do in javascript in the tweak_buttons.js file.

**Comment by cecilia-donnelly** [comment]
@cwebber yes, the lower right "done" button.  This is a desired UI change across all pages because many of them just have one column of entry fields on the left/center of the page and the Done button is far away on the bottom right.  Not super high priority, but a "nice to have."

**Comment by cwebber** [comment]
Done via css
