### ISSUE TITLE
Sign-in sheet: Why do we conditionalize Institution when row is in edit mode?

### ISSUE THREAD

**Issue by kfogel** [OpenTechStrategies/swoptact#83]
Background: In commit e3d51430a1, I made an explicit conditional for presenting null phone number on the Sign-in sheet interface.  The conditional is in `swoptact/static/js/inline_ajax.js:fillStaticRow()` and is modeled on the conditional for `participant.institution` that was already present in that function.

Below that function is another, `fillEditRow()`.  I did _not_ make the corresponding change in `fillEditRow()` because it's already working as-is, for phone number -- no conditional seems to be necessary there, because apparently when `appendSimpleTextField()` is passed a null first argument, it just puts nothing in the resulting text field box (whereas above, in `fillStaticRow()`, the corresponding call to `appendSimpleText` causes the literal word "null" to be inserted as text into the page).

So that's great -- it's working, yay.

But my question is: in `fillEditRow`, then why *is* there a conditional for `participant.institution`?  Is it because, unlike `participant.phone_number`, the `__str__()` method for `participant.institution` doesn't return what we want, and that's why we're using `participant.institution.name` instead, in both functions?  (I guess my entire question could have been rephrased to be about the use of `.name()` in the one case and the lack of `.name` in the other -- it's really "Why do we have to use `institution.name` at all?  Why isn't there an implicit `__str__()` method on institutions in the first place?)

Just curious.

**Comment by cwebber** [comment]
So the main thing is that when I handed things over, the Institution stuff was not done.  I got as much as I could done in that sprint, but the handling of "institution" stuff was stubbed out.  As you can see from [this comment on #13](https://github.com/OpenTechStrategies/swoptact/issues/13#issuecomment-94592333), institution handling was not done.

The reason for this is that unlike the other fields, institution is not simply a textbox that can be filled in.  It's a foreign key, so a whole different widget needs to be put in place.

As for why there's a conditional there, I can't really say... at the time that I passed things off, the institution was never filled in at all, it was simply displayed in the static representation.  In 9f2bce41 the condition was added by @cecilia-donnelly.  That commit by Cecelia seems to explain that this was more or less placeholder so that it showed something, but that the institution code was known to not work at this time:

```
commit 9f2bce41fd91d0b2868c256310830e65b429a9f5
Author: cecilia-donnelly <donnelly.cecilia1@gmail.com>
Date:   Mon Apr 20 17:43:31 2015 -0500

    #13: Add institution, display new person as static row.
    
    Add institution as a column on the sign-in sheet.  Make a newly created person
    show up correctly as a static row on save.
    
    The institution and address are currently not editable from the sign in sheet.
    Both should be editable and optional (which they are not, currently).  Currently
    participants created on the sign in sheet are not editable on the sign in sheet,
    because they aren't linked to an institution.  This commit also includes a
    workaround where new participants are linked to address "1" in order to be able
    to save them without an address, which will break if another implementation
    doesn't have an address with id "1."  The thing to do here is to show the
    dropdowns of institutions and addresses as django does elsewhere.  Later I think
    we want to make new institutions and addresses create-able from this page, but
    probably not today.
    
    This commit also removes the leftover ParticipantInline class from our failed
    attempt at using built-in django functionality to make the sign-in-sheet form.
    
    SaveParticipant() remains ugly for another commit.
```

So, what about the __str___ representation?  That was a something added by me while I was burning the midnight oil getting things ready for handoff.  Since the actual field on the model is a foreign key, but we needed to show the acutal representation of the model on the other end, I figured it didn't make sense to just show a dictionary of the serialized object or an integer, but the string representation we have in python, since that's already a nice human readable representation of the linked model.  But it's for display only... it's just a representation, it's *not* useful for editing.

So the real thing here is, someone needs to add a way to actually select an institution if not already selected on this ajax form.  That still hasn't been done yet.

**Comment by cecilia-donnelly** [comment]
I think this is covered by #87.  We have the conditional as a placeholder, as @cwebber says, but in #87 we're explicitly stating that we need to make the Institution editable there.  Closing this as a duplicate.
