### ISSUE TITLE
Permissions and access: alter the "Home" in the breadcrumb

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/swoptact#84]
We are currently using groups in our tagging module (to determine who can add tags, and which tags they can use), but we also need to use groups to determine which logged-in users have access to the "Groups" and "Users" sections of the app.  Presumably, only "admin" level users should be able to add users and alter user privileges.  To that end, only those users should be able to see the "home" page of the app.  

UI notes, not the main point of this issue:
Only very vaguely related, but I think we should also rename "Home" to "Admin" when it appears in the breadcrumb.

See issue #19, too.  We might be completely altering the navigation experience here, not just renaming an element in the breadcrumb.

**Comment by xray7224** [comment]
I think instead of that with the groups and permissions we've established in #138 we should just make their "Home" appropriate for them, e.g. if they are in the "leader" group and don't have access to User and Group instead it simply doesn't show up anywhere but if they are in "admin" it does because it's appropriate for them.

I think this makes way more sense than limiting the general home to admins and renaming it. It also has the advantage if we use other apps beyond our own "swoptact" app in the future it will allow us to show those if they're appropriate for that user on the home.

**Comment by cecilia-donnelly** [comment]
@xray7224, that sounds right to me.  It looks like this is already happening after commit f5b5fae.
