### ISSUE TITLE
Institution: Each Contact should be a directly editable field tied to Participant model.

### ISSUE THREAD

**Issue by kfogel** [OpenTechStrategies/swoptact#94]
As of right now (commit c7172d01cc is current HEAD), the inline Contacts list on an Institution page (e.g., http://localhost:8000/swoptact/institution/2/) displays the Contacts' names in an ungainly way.  The name is shown twice in the left column:

* As a standard autocomplete potentially-editable field showing the Participant name (and editable if you click the misleading "X" in a circle, the one that looks like it means "Remove" but really means "Edit this field, except that when I open up the text field I'm not going to populate it with the name that was originally there and that you clicked on, so now you'll be totally confused, hahahahaha");
* As a straight HTML link to that Participant's profile.

We should replace this with a much easier UI:

* An editable text field pre-populated with the Contact's name, where if you click in there and start editing it autocompletes among Participants but allows you to put in a totally new name too (and if you finalize on a new name that is not the name of any existing Participant, the Phone Number field to the right should be cleared of course, and then when you submit that new Participant would be created with just the name, or with the name and phone number if you give them a phone number);
* A little `[i]` information link (e.g., the Unicode "source information" character &#x2139;) that links to that Participant's profile.

**Comment by kfogel** [comment]
Notes on next steps:

In the `swoptact/admin.py:ContactInline` class, we are using `st_forms.autocomplete_modelform_factory`.  That implies some mods in `swoptact/forms.py` to make this work as desired.  (Thanks to @cecilia-donnelly for the pointers.)

**Comment by cecilia-donnelly** [comment]
@kfogel, @nttaylor has some interest in picking this one up.  Can you two coordinate?  I know you (@kfogel) are somewhat in the middle of it, and didn't want to interrupt, but Noel has been making very speedy progress through several other issues and wants to learn more about what's going on here.

**Comment by cwebber** [comment]
Sounds a lot like what's happening in #48, but without many to many fields.  Perhaps the efforts there should be merged.

More importantly, it's maybe significant information that the django autocomplete frontend's default look and feel is being deemed insufficient and that this UI is being proposed, which seems like a break from the stuff we get from django_autocomplete_light, it might make sense then to do something custom that tries to incorporate both the work here and that in 48.  I'm looking into exploring just the jquery-autocomplete library but using the django_autocomplete_light registry as a quicker bootstrapping, will report back.

**Comment by kfogel** [comment]
Assigning to @nttaylor, based on @cecilia-donnelly's question a few comments back.  My connectivity isn't reliable enough for me to make speedy progress on this.  Noel, do talk to @cwebber and see if/how this work is related with similar things he's doing on other pages.

The changes I made in commit acb6c456c4fdc are probably worth looking at, just to help you zero in on the place where further changes will likely be needed.

**Comment by cecilia-donnelly** [comment]
Assigning back to @kfogel, since you will now be here and @nttaylor won't.  Note that at the moment no text box or editable area at all is showing up in the "add another key contact" row, though existing contacts are editable and autocompletion is working.

Check out @cwebber's work on #87 to help with this.

**Comment by cwebber** [comment]
So much has been done on this:
 - Functions have been documented
 - There has been a massive rewrite of varibles changing "event" to "base model" and "participant" to "inline model", including all the case complexity.
 - I've written some code so that in admin.py you can specify which data configuring things will be passed to the javascript application.  This is serialized to json then passed to the template, allowing us to have a nice general way to configure the javascript side for different models and pages, a real step towards making this tool generic.

Next up will be:
 - Removing all hardcoded API paths and etc and moving into the configuration slot in admin.py
 - Similarly, removing hardcoded "which field is what structure"; this will have to permit different kinds of fields similar to how django form fields work.
 - Finally, need to convert the Institution page.  This may require a little bit of API tweak or adding new endpoints, not sure.

We seem to be on or ahead of schedule for my EOD July 15th estimate, which is good news!

**Comment by cwebber** [comment]
Oh yes and:
 - A few functions in inline_ajax.js need to be rewritten, but that should fit in the time allocation I think.

**Comment by cwebber** [comment]
Okay, I pushed commits to make this code fairly generic.  The field type handling still needs to be done too, but we're very near the point of converting other pages to use this, and I think we can convert over the institution pages tomorrow!

**Comment by cwebber** [comment]
As of d21ee4d we can now save data based on how the form is configured in admin.py.

I left some long comments in that commit.  [This one in particular is a bit lengthy](https://github.com/OpenTechStrategies/swoptact/commit/d21ee4d125d8d5b37196dac8f22d1bcfdf939128#diff-30a13fb70acb17dd5ab9acd90e9f53a9R685) but someone could easily do a test of it to see how Django's API behaves... we might be able to simplify both code and comments based on that.

The good news: now it's time to convert the Institution page!

**Comment by cecilia-donnelly** [comment]
@cwebber thank you!  I'll volunteer to do the test you mention, probably tomorrow (if not tonight).

**Comment by cwebber** [comment]
Thanks @cecilia-donnelly!  (Also wow, that was a fast response! :))

**Comment by cecilia-donnelly** [comment]
This is done (hurray @cwebber!), but I'm going to replace the link to the participant profile before closing, since that was part of the original ticket.

**Comment by cecilia-donnelly** [comment]
I added those links in 69f4ad8, and thanks to @cwebber's tremendous efforts am now closing this ticket.
